// Word of the day — English word, Persian meaning, short example.
export type Word = { en: string; fa: string; ex: string }

export const WORDS: Word[] = [
  { en: 'resilient', fa: 'تاب‌آور، مقاوم', ex: 'A resilient system recovers quickly from failure.' },
  { en: 'leverage', fa: 'اهرم کردن، بهره بردن', ex: 'Leverage automation to save time.' },
  { en: 'robust', fa: 'قوی، پایدار', ex: 'We need a robust backup strategy.' },
  { en: 'seamless', fa: 'یکپارچه، بی‌درز', ex: 'The migration was seamless.' },
  { en: 'scalable', fa: 'مقیاس‌پذیر', ex: 'Design a scalable architecture from day one.' },
  { en: 'concise', fa: 'مختصر و مفید', ex: 'Keep your commit messages concise.' },
  { en: 'ambiguous', fa: 'مبهم، دوپهلو', ex: 'The requirement was ambiguous.' },
  { en: 'deprecate', fa: 'منسوخ کردن', ex: 'They deprecated the old API.' },
  { en: 'idempotent', fa: 'خنثی به تکرار (بی‌اثر بودن تکرار)', ex: 'Make the script idempotent so re-runs are safe.' },
  { en: 'granular', fa: 'ریزدانه، جزئی', ex: 'Set granular permissions per user.' },
  { en: 'mitigate', fa: 'کاهش دادن، تخفیف دادن', ex: 'Caching helps mitigate load.' },
  { en: 'redundant', fa: 'اضافی، افزونه', ex: 'Keep redundant backups off-site.' },
  { en: 'throttle', fa: 'محدود کردن نرخ', ex: 'Throttle requests to avoid rate limits.' },
  { en: 'bottleneck', fa: 'گلوگاه', ex: 'The database was the bottleneck.' },
  { en: 'boilerplate', fa: 'کد تکراری/قالبی', ex: 'Generators remove boilerplate.' },
  { en: 'graceful', fa: 'نرم، بی‌دردسر', ex: 'Handle errors with a graceful fallback.' },
  { en: 'orchestrate', fa: 'هماهنگ/ارکستر کردن', ex: 'Compose orchestrates the containers.' },
  { en: 'provision', fa: 'فراهم/آماده‌سازی', ex: 'Provision the server before deploy.' },
  { en: 'ephemeral', fa: 'زودگذر، موقتی', ex: 'Containers are ephemeral by design.' },
  { en: 'immutable', fa: 'تغییرناپذیر', ex: 'Prefer immutable infrastructure.' },
  { en: 'latency', fa: 'تأخیر', ex: 'Low latency improves UX.' },
  { en: 'overhead', fa: 'سربار', ex: 'This adds little overhead.' },
  { en: 'streamline', fa: 'ساده و روان کردن', ex: 'Streamline your workflow.' },
  { en: 'intuitive', fa: 'شهودی، آسان‌فهم', ex: 'The UI should be intuitive.' },
  { en: 'versatile', fa: 'همه‌کاره، انعطاف‌پذیر', ex: 'A versatile tool for many tasks.' },
  { en: 'meticulous', fa: 'دقیق و وسواسی', ex: 'Be meticulous with backups.' },
  { en: 'pragmatic', fa: 'عمل‌گرا، واقع‌بین', ex: 'Take a pragmatic approach.' },
  { en: 'coherent', fa: 'منسجم، هماهنگ', ex: 'Keep a coherent design system.' },
  { en: 'arbitrary', fa: 'دلخواه، اختیاری', ex: 'Avoid arbitrary limits.' },
  { en: 'explicit', fa: 'صریح، آشکار', ex: 'Be explicit in your config.' },
  { en: 'implicit', fa: 'ضمنی، تلویحی', ex: 'Avoid implicit assumptions.' },
  { en: 'verbose', fa: 'پرحرف، پرجزئیات', ex: 'Verbose logs help debugging.' },
  { en: 'obsolete', fa: 'منسوخ، از رده خارج', ex: 'That library is obsolete.' },
  { en: 'feasible', fa: 'شدنی، عملی', ex: 'Is this feasible by Friday?' },
  { en: 'holistic', fa: 'کل‌نگر', ex: 'Take a holistic view of the stack.' },
  { en: 'nuance', fa: 'ظرافت، تفاوت جزئی', ex: 'There is a nuance here.' },
  { en: 'leverage', fa: 'نفوذ، قدرت چانه‌زنی', ex: 'Data gives you leverage.' },
  { en: 'tedious', fa: 'خسته‌کننده، کسل‌کننده', ex: 'Automate tedious tasks.' },
  { en: 'compelling', fa: 'متقاعدکننده، جذاب', ex: 'A compelling product demo.' },
  { en: 'sophisticated', fa: 'پیچیده و پیشرفته', ex: 'A sophisticated caching layer.' },
  { en: 'agile', fa: 'چابک، سریع', ex: 'Stay agile and iterate.' },
  { en: 'iterate', fa: 'تکرار/بازنگری کردن', ex: 'Iterate fast, ship often.' },
  { en: 'consolidate', fa: 'یکپارچه/تجمیع کردن', ex: 'Consolidate tools into one hub.' },
  { en: 'benchmark', fa: 'محک، معیار سنجش', ex: 'Benchmark before optimizing.' },
  { en: 'optimize', fa: 'بهینه کردن', ex: 'Optimize the hot path first.' },
  { en: 'refactor', fa: 'بازآرایی کد', ex: 'Refactor for readability.' },
  { en: 'validate', fa: 'اعتبارسنجی کردن', ex: 'Always validate user input.' },
  { en: 'delegate', fa: 'واگذار کردن', ex: 'Delegate work to sub-agents.' },
  { en: 'prioritize', fa: 'اولویت‌بندی کردن', ex: 'Prioritize high-impact tasks.' },
  { en: 'sustainable', fa: 'پایدار، ماندگار', ex: 'Build at a sustainable pace.' },
  { en: 'proactive', fa: 'پیش‌کنشی، پیش‌بینانه', ex: 'Be proactive about security.' },
  { en: 'redundancy', fa: 'افزونگی', ex: 'Redundancy prevents downtime.' },
  { en: 'threshold', fa: 'آستانه، حد', ex: 'Alert when CPU crosses the threshold.' },
  { en: 'anomaly', fa: 'ناهنجاری، استثنا', ex: 'The monitor flagged an anomaly.' },
  { en: 'converge', fa: 'همگرا شدن', ex: 'The results converge over time.' },
  { en: 'diverge', fa: 'واگرا شدن', ex: 'Their opinions diverge.' },
  { en: 'reliable', fa: 'قابل‌اعتماد', ex: 'A reliable deployment pipeline.' },
  { en: 'trivial', fa: 'جزئی، ناچیز', ex: 'That is a trivial change.' },
  { en: 'subtle', fa: 'ظریف، نامحسوس', ex: 'A subtle but important bug.' },
  { en: 'coherence', fa: 'انسجام', ex: 'Design coherence matters.' },
  { en: 'aggregate', fa: 'تجمیع/گردآوری کردن', ex: 'Aggregate logs in one place.' },
  { en: 'encapsulate', fa: 'کپسوله/محصور کردن', ex: 'Encapsulate the logic in a module.' },
  { en: 'abstraction', fa: 'انتزاع', ex: 'A clean abstraction hides complexity.' },
  { en: 'deterministic', fa: 'قطعی، معین', ex: 'Keep builds deterministic.' },
  { en: 'concurrent', fa: 'هم‌زمان', ex: 'Run tasks concurrently.' },
  { en: 'asynchronous', fa: 'ناهم‌زمان', ex: 'Use asynchronous calls for I/O.' },
  { en: 'persistent', fa: 'پایدار، ماندگار', ex: 'Store data in a persistent volume.' },
  { en: 'volatile', fa: 'ناپایدار، فرّار', ex: 'RAM is volatile memory.' },
  { en: 'legacy', fa: 'قدیمی، موروثی', ex: 'Maintain the legacy system.' },
  { en: 'robustness', fa: 'استحکام', ex: 'Test for robustness under load.' },
  { en: 'elegant', fa: 'ظریف، شیک', ex: 'An elegant solution.' },
  { en: 'redundant', fa: 'زائد، تکراری', ex: 'Remove redundant code.' },
  { en: 'streamlined', fa: 'روان‌شده، بهینه', ex: 'A streamlined checkout flow.' },
  { en: 'insightful', fa: 'بصیرت‌بخش، عمیق', ex: 'An insightful analysis.' },
  { en: 'resourceful', fa: 'کاردان، چاره‌ساز', ex: 'A resourceful engineer.' },
  { en: 'thorough', fa: 'کامل، دقیق', ex: 'Do a thorough review.' },
  { en: 'concurrent', fa: 'موازی، هم‌زمان', ex: 'Handle concurrent users.' },
  { en: 'incremental', fa: 'تدریجی، مرحله‌ای', ex: 'Ship incremental improvements.' },
  { en: 'paramount', fa: 'بسیار مهم، حیاتی', ex: 'Security is paramount.' },
  { en: 'redundancy', fa: 'پشتیبان‌گیری موازی', ex: 'Add redundancy for uptime.' },
  { en: 'streamline', fa: 'تسریع و ساده‌سازی', ex: 'Streamline onboarding.' },
  { en: 'cohesive', fa: 'منسجم، به‌هم‌پیوسته', ex: 'A cohesive team ships faster.' },
  { en: 'diligent', fa: 'کوشا، پرتلاش', ex: 'Be diligent with testing.' },
  { en: 'adept', fa: 'ماهر، چیره‌دست', ex: 'She is adept at debugging.' },
  { en: 'foster', fa: 'پرورش دادن، تقویت کردن', ex: 'Foster a learning culture.' },
  { en: 'streamlining', fa: 'روان‌سازی', ex: 'Streamlining reduces friction.' },
  { en: 'endeavor', fa: 'تلاش، کوشش', ex: 'A worthwhile endeavor.' },
  { en: 'facilitate', fa: 'تسهیل کردن', ex: 'Tools facilitate collaboration.' },
  { en: 'inherent', fa: 'ذاتی، درونی', ex: 'An inherent trade-off.' },
  { en: 'redundant', fa: 'مازاد', ex: 'The check is redundant.' },
  { en: 'versatility', fa: 'همه‌کارگی', ex: 'The versatility of the tool.' },
  { en: 'streamline', fa: 'کارآمد کردن', ex: 'Streamline the build.' },
]
